// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn87wS8faYVwH7GLBNbiS68RbNP_ZQ1L8',
    appId: '1:401301010020:web:77760eb94d100a26b81171',
    messagingSenderId: '401301010020',
    projectId: 'servigo-99fc4',
    authDomain: 'servigo-99fc4.firebaseapp.com',
    storageBucket: 'servigo-99fc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjkQTJ2wBKhbM7QH1nxIMaLkrpEnSmQsM',
    appId: '1:401301010020:android:6e44a6a3009c9905b81171',
    messagingSenderId: '401301010020',
    projectId: 'servigo-99fc4',
    storageBucket: 'servigo-99fc4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn87wS8faYVwH7GLBNbiS68RbNP_ZQ1L8',
    appId: '1:401301010020:web:ec6285a1c379fe1db81171',
    messagingSenderId: '401301010020',
    projectId: 'servigo-99fc4',
    authDomain: 'servigo-99fc4.firebaseapp.com',
    storageBucket: 'servigo-99fc4.firebasestorage.app',
  );
}
